import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const repoRoot = resolve(process.cwd());
const mockDir = join(repoRoot, "worker", "mock-data");
const outPath = join(repoRoot, "worker", "mock-data.generated.ts");

const files = readdirSync(mockDir, { withFileTypes: true })
  .filter((ent) => ent.isFile())
  .map((ent) => ent.name)
  .sort((a, b) => a.localeCompare(b, "en"));

const entries = files.map((name) => {
  const full = join(mockDir, name);
  const text = readFileSync(full, "utf8");
  return [name, text];
});

const lines = [];
lines.push("// This file is generated by `node scripts/gen-mock-kv.mjs`.");
lines.push("// DO NOT EDIT MANUALLY.");
lines.push("");
lines.push("export const MOCK_KV: Record<string, string> = {");
for (const [k, v] of entries) {
  lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
}
lines.push("};");
lines.push("");

writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`[gen-mock-kv] wrote ${outPath} (${files.length} keys)`);

